source 'https://rubygems.org'

gem 'em-websocket', '~> 0.5.1'
gem 'em-pg-client', '~> 0.3.4'
gem 'pg'

gem 'activesupport', '~>4.1'
gem 'activerecord', '~>4.1'
gem 'bcrypt-ruby', '~> 3.1.5'

gem 'rake'

gem 'rspec'

gem 'faker'
