#!/usr/bin/env bash

if [ -e "context.pid" ]
then
  pid=`cat context.pid`
  if ps -p $pid > /dev/null
  then
    echo "Process $pid is alive and well."
  else
    echo "Process $pid is dead."
  fi
else
  echo "context.pid doesn't exist"
fi